### ISSUE TITLE
[wifi-login-pages] Implement change phone number for active users

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#106]
To be done after https://github.com/openwisp/openwisp-radius/issues/179 is resolved.

This app has a change phone number component which is meant for inactive users to change their phone number, in case they mistakenly used a wrong phone number during registration.

- [ ] we have to change the component so it allows verified users to use it, right now active users get redirected to status
- [ ] add a test for the functionality described in the previous point
- [ ] we have to ensure the whole flow works:
  - change phone number generates a new SMS token, flags user as inactive and user is redirected to mobile verification component
  - once user confirms the SMS token, it's flagged as active again, their phone number is correctly updated and is redirected to status component 
- [ ] change the org config generator so that if mobile_phone_verification is enabled, a link to change phone number is added to the header links (shown only to authenticated users)

**Comment by NoumbissiValere** [comment]
@nemesisdesign when you say `verified users` you meant active users right? If so, then  there is a problem. During the development of [PR #183](https://github.com/openwisp/openwisp-radius/pull/183), I sited that with the present implementations in `openwisp-radius`, active users can't change phone number because of [this if statement](https://github.com/openwisp/openwisp-radius/blob/master/openwisp_radius/base/models.py#L1163) and I opted to change it but you refused.

**Comment by nemesisdesign** [comment]
I hope the next steps are clear after our exchange, in short: both active and inactive users need to be able to change their phone number, but if an active user does this, it's flagged as inactive again until they confirm their new phone number and the old phone number is stored in the database (in the PhoneToken model). The work to do in this app should be small since the component is already developed, I just added a point (I forgot to make it explicit that we need a test) to the list.
