### ISSUE TITLE
[deps] Update history as suggested by dependabot but fix issues

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#125]
This dependabot change is failing because of a mock that seems cannot be done in that way anymore: https://github.com/openwisp/openwisp-wifi-login-pages/pull/117.
There should be another recommended way of accomplishing the same thing, we should find it and replace those lines that cause the build failure.

**Comment by Uttkarsh10** [comment]
I would be interested in resolving this bug.

**Comment by Mayank-contradiction** [comment]
Is this issue still open?

**Comment by nemesisdesign** [comment]
Yes the issue is still hoping, anyone that wants to help out just send a PR @Uttkarsh10 @Mayank-contradiction.

**Comment by Ayushsunny** [comment]
Hello @nemesisdesign where to find code base of this issue?

**Comment by garvitchittora** [comment]
@nemesisdesign this is fixed, right?

![Screenshot from 2021-03-20 15-53-54](https://user-images.githubusercontent.com/54021348/111866584-85546d80-8994-11eb-8b62-d44e36f2616b.png)

**Comment by Purhan** [comment]
@garvitchittora @Ayushsunny this issue is not a feature request, nor is it something in the existing code.

Look at the PR #117

The task is to upgrade the `history` dependency package like it's done in #117, but that would cause some tests to fail as some things might be changed to work differently in the newer version of the dependency. You have to fix those errors (debug what's causing that error). Anyone who wants to help, just send a PR.

To know which tests failed, you can check [this log](https://travis-ci.com/github/openwisp/openwisp-wifi-login-pages/builds/203068180) and also run the tests manually in your local repository as per the instructions mentioned in the readme.
