### ISSUE TITLE
[bug] is_verified defaults to true

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#270]
@codesankalp try the following patch:

```diff
diff --git a/client/components/status/status.js b/client/components/status/status.js
index 5e7131c..6c221e5 100644
--- a/client/components/status/status.js
+++ b/client/components/status/status.js
@@ -88,6 +88,9 @@ export default class Status extends React.Component {
         logout,
       );
       setLoading(false);
+
+      console.log(userData);
+
       if (isValid) {
         const {justAuthenticated} = userData;
         ({userData} = this.props);
```

Now log in, first time the user data is logged in the console correctly.

Now reload the page, this time the user data is not logged and the default values are used instead.

This is giving me pain while working on https://github.com/openwisp/openwisp-wifi-login-pages/pull/170.

**Question 1**: why is that `console.log` returning the default data instead of the data we received from the server?
**Question 2**: how to we access the data which was returned from the server instead of the default data?

**Question 3**: can you explain why you default `is_verified` to `true` here?

https://github.com/openwisp/openwisp-wifi-login-pages/blob/0caf7ddeb0eb126a1eb35104f7638ec8bd8f5aea/client/reducers/organization.js#L18-L27

**Question 4**: why is this information duplicated 2 more times?

https://github.com/openwisp/openwisp-wifi-login-pages/blob/0caf7ddeb0eb126a1eb35104f7638ec8bd8f5aea/client/actions/set-organization.js#L23-L27

https://github.com/openwisp/openwisp-wifi-login-pages/blob/0caf7ddeb0eb126a1eb35104f7638ec8bd8f5aea/client/actions/set-organization.js#L43-L45

We should define this information only once and I believe `is_verified` should default to `null`.

**Comment by nemesisdesign** [comment]
Please review this PR to see if it's an acceptable solution: https://github.com/openwisp/openwisp-wifi-login-pages/pull/271
If not please explain and propose a better one.

**Comment by codesankalp** [comment]
> **Question 1**: why is that `console.log` returning the default data instead of the data we received from the server?

Before validating the token the userData is the data of the initial state.

> **Question 2**: how to we access the data which was returned from the server instead of the default data?

After validating the token it will give user data.

> **Question 3**: can you explain why you default `is_verified` to `true` here?
> https://github.com/openwisp/openwisp-wifi-login-pages/blob/0caf7ddeb0eb126a1eb35104f7638ec8bd8f5aea/client/reducers/organization.js#L18-L27

Without initial state `is_verified` is undefined which is needed in organization-wrapper for routing, so just to provide its default behavior I added it in the initial state. I provide its value to true so that it will not redirect to the mobile verification page if the user is already verified. But in #271, the condition check for needsMobilePhoneVerification is more specific.

> **Question 4**: why is this information duplicated 2 more times?
> 
> https://github.com/openwisp/openwisp-wifi-login-pages/blob/0caf7ddeb0eb126a1eb35104f7638ec8bd8f5aea/client/actions/set-organization.js#L23-L27
> 
> https://github.com/openwisp/openwisp-wifi-login-pages/blob/0caf7ddeb0eb126a1eb35104f7638ec8bd8f5aea/client/actions/set-organization.js#L43-L45

The first one is for using `userData` in organization configuration, and the other is for providing a default value for the `SET_USER_DATA` action.

> We should define this information only once and I believe `is_verified` should default to `null`.

Yes, I saw the PR and condition for checking the need for mobile verification is more specific which resolves this bug.
