### ISSUE TITLE
[UI] Integrate react-toast-notifications and show notifications for events

### ISSUE THREAD

**Issue by Vivekrajput20** [openwisp/openwisp-wifi-login-pages#45]
Integrate [react-toast-notifications](https://www.npmjs.com/package/react-toast-notifications) with the app. Or propose any better package to show notifications to the user.
Show toast notifications to user for success and error events in all the pages including Login, Registration and Status page.

**Comment by nikitaermishin** [comment]
@Vivekrajput20 I want to propose to use [react-toastify](https://www.npmjs.com/package/react-toastify) because with it we musn't use `React hooks` (as with [react-toast-notifications](https://www.npmjs.com/package/react-toast-notifications)), so we mustn't switch from `class`es to `function`s. 
***
Also I want to know if we should notify user not only about the fact, that the error occurred, but also about the error description and internal state.

**Comment by Vivekrajput20** [comment]
@nikitaermishin you're confusing React hooks with hooks. We can't always render Toasts inside the Render by creating a component for it. For uncertain circumstances like response of an API request, we use hooks to alter the components. Suppose we are making an API request inside `handleSubmit` function. With hooks we can directly show the notification toast to user by defining something like 
`addToast(error.message, { appearance: 'error' })` instead of storing the response to our state and then checking the state in render method and manually rendering the Toast Component if there is a notification. [react-toastify](https://www.npmjs.com/package/react-toastify) also uses hooks for accomplishing this. Many other packages use hooks and React is one of them to use hooks in functional components.
